# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200317_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goodstype',
            new_name='goodsType',
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='title',
            field=models.CharField(max_length=20, verbose_name='品类名称'),
        ),
    ]
